---
- name: Install and configure yolomy e-commerce microservices.
  hosts: all
  become: yes
  roles:
    - update_ubuntu
    - docker_installation
    - clone_yolo_repo
    - create_docker_network
    - create_db_docker_image
    - create_backend_docker_image
    - create_frontend_docker_image
    - use_nginx