---
# vars file for use_nginx
image: nginx:alpine
container_name: nginx_server
container_ports: "80:80"
network_name: app_network
persistent_nginx_path: /etc/nginx/
persistent_nginx_conf_path: /etc/nginx/nginx.conf
container_volumes: /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
ansible_user: vagrant